---
name: CMake

on:
  push:
    branches:
      - master
      - develop

    paths:
      - '**.cpp'
      - '**.hpp'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - '.github/workflows/**.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo
  CTEST_OUTPUT_ON_FAILURE: 1
  CMAKE_EXPORT_COMPILE_COMMANDS: 1

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false

      matrix:
        config:
          - {name: "Windows", os: windows-latest, cc: "clang-cl", cxx: "clang-cl"}
          - {name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc-10", cxx: "g++-10"}
          - {name: "Ubuntu clang", os: ubuntu-latest, cc: "clang-12", cxx: "clang++-12"}
          - {name: "MacOS apple-clang", os: macos-latest, cc: "clang", cxx: "clang++"}

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Install llvm-12 Ubuntu Host
        if: startsWith(matrix.config.name, 'Ubuntu')
        shell: bash
        run: |
          sudo apt-get install \
            llvm-12 clang-12 libclang-12-dev clang-tidy-12

      - name: Configure cmake on Windows build host
        if: runner.os == 'Windows'
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Configure cmake
        if: runner.os != 'Windows'
        shell: bash
        working-directory: ${{github.workspace}}/build
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}

        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE

      - name: Run clang-tidy on Ubuntu build host
        if: startsWith(matrix.config.name, 'Ubuntu')
        working-directory: $GITHUB_WORKSPACE
        shell: bash
        run: run-clang-tidy-12 -p ${{github.workspace}}/build example/basic.cpp

      - name: Run clang-tidy on MacOS build host
        if: startsWith(matrix.config.name, 'MacOS')
        working-directory: $GITHUB_WORKSPACE
        shell: bash
        run: |
          # brew install llvm
          export PATH=/usr/local/opt/llvm/bin/:${PATH}
          run-clang-tidy -p ${{github.workspace}}/build example/basic.cpp

      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: build
          key: ${{matrix.config.name}}
